apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager
  - cloudflare-tunnel
  - longhorn
  - metrics-server
  - rbac
  - traefik
  - victoria-logs
  - victoria-metrics
