apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cluster.yaml
  - ingredients-role-password.yaml
  - database-ingredients.yaml
  - recipes-role-password.yaml
  - database-recipes.yaml
  - pantry-role-password.yaml
  - database-pantry.yaml
