apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: woodpantry-matching
  namespace: flux-system
spec:
  interval: 10m
  retryInterval: 1m
  path: ./kubernetes
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: woodpantry-matching
  postBuild:
    substitute:
      IMAGE_TAG: "35e8e6b"
